<?php

use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\MigrateMessage;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_cronapi().
 */
function migrate_repository_cronapi() {
  return [
    'import_repositories' => [
      'title' => 'Import repositories',
      'callback' => 'migrate_repository_cron_import_repositories',
      'callback arguments' => [],
      'scheduler' => [
        'name' => 'crontab',
        'crontab' => [
          'rules' => ['*/5+@ * * * *'],
        ],
      ],
    ],
  ];
}

/**
 * Import repositories.
 */
function migrate_repository_cron_import_repositories() {
  $migration = \Drupal::service('plugin.manager.migration')->createInstance('json_repository');
  if ($migration) {
    $executable = new MigrateExecutable($migration, new MigrateMessage());
    $executable->import();
  }
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function migrate_repository_taxonomy_term_insert() {
  migrate_repository_cron_import_repositories();
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function migrate_repository_taxonomy_term_delete(Term $term) {
  $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'field_language' => $term->id(),
  ]);
  $controller = \Drupal::entityManager()->getStorage('node');
  $controller->delete($nodes);
}
