module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  block: 0
  breakpoint: 0
  config: 0
  custom_page: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  filter: 0
  link: 0
  migrate: 0
  migrate_plus: 0
  migrate_repository: 0
  migrate_tools: 0
  node: 0
  page_cache: 0
  react_app: 0
  rest: 0
  serialization: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  ultimate_cron: 0
  user: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
